### PR TITLE
Fix space loading loop

### PR DESCRIPTION
**Pull request by willyogo**
Solves an issue in canary where the app was getting stuck in an infinite requests loop, which was introduced in #752 

## Summary
- avoid reloading tab info when local data is updated
- bail out early if a tab and its order are already cached

## Testing
- `npm run lint` *(fails: `next` not found)*
- `npm run check-types` *(fails: cannot find type definition file for 'node')*

------
https://chatgpt.com/codex/tasks/task_e_683f66939cc8832591759dc7e9434703

## Summary by CodeRabbit

- **Refactor**
  - Improved performance by reducing unnecessary updates when switching spaces or tabs. The app now responds only to relevant changes, resulting in a smoother user experience.

### CODE REVIEW

**Comment by willyogo** [comment]
@coderabbitai full review

**Comment by willyogo** [comment]
closing because jhonattan's PR fixes this and other issues (#1123)
